### ISSUE TITLE
BTC Supply Service

### ISSUE THREAD

**Issue by hleb-albau** [cybercongress/cyber-search#194]
#### Overview
[Here](https://github.com/cybercongress/cyber-search/blob/master/README.md) you can explore our project

---
#### Task description

Create standalone service for calculation bitcoin supply.
Service should read bitcoin block kafka topic, and produce new supply values for chain.supplyTopic kafka topic.

---
#### Required skills

- Kotlin
- Gradle
- Kafka
- Bitcoin Internals

---
#### Contribution rules

[Here](https://github.com/cybercongress/cyber-search/blob/master/docs/contributing/contributing.md) you can learn how to contribute to our project

---
#### Definition of done

Reflect modules:  `:supply:bitcoin`
Examples: See ETH implementations #166.
Formula: Bitcoin supply calculated only by bitcoin block rewards.

- [ ] Write new service to calculate BTC supply
- [ ] Code coverage > 85% for created service
- [ ] Docker image and CI

**Comment by SaveTheAles** [comment]
@hleb-albau  @xhipster 
This is just task description. To avoid extra questions from contributors I propose add:
- [ ] small introduction section with project describing (OR just a link to README.md); 
- [ ] current project situation section where you can explain why we need to solve this task;
- [ ] after them task description goes;
- [ ] required skills;
- [ ] contributing rules (OR just link to CONTRIBUTING.md);
- [ ] clear definition of done (what you actually need to see as result of work);
- [ ] specially for me: fund amount, expires in, experience level, project length and bounty type (iptional).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.3 ETH (178.29 USD @ $594.3/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/cybercongress/cyber-search/194/569).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $10,104.58 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 2 weeks, 1 day from now. Please review their questions below:


1. [rafaelboyero](https://gitcoin.co/profile/rafaelboyero) has started work.

**Comment by hleb-albau** [comment]
Hi @KevinLiLu! Yes, feel free to ask questions!

**Comment by hleb-albau** [comment]
Yes, pumping part already there. Also, there is env variable to adjust start block number.

Yes, task is to read  from kafka chain.block topic, update bitcoin supply(how many bitcoins already mined). To get bitcoin supply, just read last value from chain.supplyTopic( or 0 if topic not exist).

No need to create new message for every block, we can use batch record processing.

I updated link for overview.

Thanks. @KevinLiLu

**Comment by KevinLiLu** [comment]
@hleb-albau Is there somewhere I can message you directly for any further questions?

**Comment by arturalbov** [comment]
Hi!
You could ask your questions directly to my Telegram - @arturalbov

**Comment by KevinLiLu** [comment]
Hi @arturalbov , sure thing. I have registered on Gitcoin with this task. I will join the Telegram sometime soon (gone for the weekend so probably on Monday)!

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 0.3 ETH (120.6 USD @ $402.01/ETH) has been submitted by__:

 1. [@KevinLiLu](https://gitcoin.co/profile/KevinLiLu)



@hleb-albau please take a look at the submitted work:
* [PR](https://github.com/cybercongress/cyber-search/pull/250) by @KevinLiLu

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/cybercongress/cyber-search/194/569)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/cybercongress/cyber-search/194/569).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $27,651.26 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by hleb-albau** [comment]
Hi @KevinLiLu, today I will test your PR. Thanks for waiting.

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 0.3 ETH (125.47 USD @ $418.25/ETH)  attached to this issue has been approved & issued to @KevinLiLu.__  

 * Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/cybercongress/cyber-search/194/569)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $25,458.96 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 0.3 ETH (125.47 USD @ $418.25/ETH)  attached to this issue has been approved & issued to @KevinLiLu.__  

 * Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/cybercongress/cyber-search/194/569)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $25,458.96 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
